import os
import time
import csv
import json
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# --- 1. CONFIGURATION & ABSOLUTE FIDELITY ---
ENGINE_DIR = r"C:\Users\Ofthe\SovereignNexus\src\Engine_V2"
TASK_QUEUE = os.path.join(ENGINE_DIR, "03_MEDIUM_TASKS", "task_queue")
INVOICE_DRAFTS = os.path.join(ENGINE_DIR, "01_FINANCE", "Invoices", "_drafts")
VERIFIED_BASE = os.path.join(ENGINE_DIR, "01_FINANCE")

# Ensure directories exist
os.makedirs(INVOICE_DRAFTS, exist_ok=True)

# --- 2. TRANSFORMATION LOGIC ---
def process_signal(signal_path):
    """Answers the signal, parses verified data, and drafts an invoice."""
    try:
        # Read Signal Info
        with open(signal_path, 'r') as sf:
            lines = sf.readlines()
            source = lines[0].split(": ")[1].strip()
            filename = lines[1].split(": ")[1].strip()

        print(f"\n[TIER 2] Answering Signal for {source}: {filename}")

        # Locate Verified File
        if source == "CASH APP":
            verified_path = os.path.join(VERIFIED_BASE, "Cash_App", "_verified_ledger", filename)
        elif source == "INBOUND_SIGNAL":
            verified_path = os.path.join(ENGINE_DIR, "02_MICRO_FLOW", "constant_flow_logs", filename)
        else:
            verified_path = os.path.join(VERIFIED_BASE, "Novo_Account", "_verified_ledger", filename)

        if not os.path.exists(verified_path):
            print(f"[ERROR] Verified file not found: {verified_path}")
            return

        # Parse CSV Data
        with open(verified_path, mode='r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            # Strip whitespace from keys for each row
            data = [{k.strip(): v for k, v in row.items()} for row in reader]

        # Generate Invoice Stub
        for row in data:
            # Create a unique ID for the draft
            tx_id = row.get("Transaction ID") or row.get("Date", "").replace(":", "").replace("-", "").replace(" ", "_")
            draft_filename = f"DRAFT_{source.replace(' ', '_')}_{tx_id}.md"
            draft_path = os.path.join(INVOICE_DRAFTS, draft_filename)

            invoice_content = f"""# SOVEREIGNNEXUS INVOICE STUB
**Source:** {source}
**Transaction ID:** {tx_id}
**Date:** {row.get('Date')}
**Counterparty:** {row.get('Name') or row.get('Description')}
**Amount:** {row.get('Amount')}
**Status:** DRAFT_VERIFIED

---
**[SYSTEM NOTE]**
This stub was autonomously generated by Engine V2 Tier 2 Processor.
1=1=1. Truth Anchored.
"""
            with open(draft_path, 'w') as df:
                df.write(invoice_content)
            
            print(f"[SUCCESS] Invoice Draft generated: {draft_filename} ({len(invoice_content)} bytes)")

        # Cleanup Signal
        os.remove(signal_path)
        print(f"[CLEANUP] Signal {os.path.basename(signal_path)} purged.")

    except Exception as e:
        print(f"[ERROR] Tier 2 Processing Failed: {e}")

# --- 3. THE LISTENER ---
class SignalHandler(FileSystemEventHandler):
    def on_created(self, event):
        if not event.is_directory and event.src_path.lower().endswith('.txt'):
            time.sleep(0.5)
            process_signal(event.src_path)

if __name__ == "__main__":
    print("==================================================")
    print(" ENGINE V2: TIER 2 PROCESSOR (STABLE)")
    print(f" Watching Queue: {TASK_QUEUE}")
    print("==================================================")
    
    event_handler = SignalHandler()
    observer = Observer()
    observer.schedule(event_handler, path=TASK_QUEUE, recursive=False)
    observer.start()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
